### ISSUE TITLE
TuningFork and Memtrack Errors

### ISSUE THREAD

**Issue by Ditronian** [android/tuningfork#39] opened 2023-08-16 20:25 UTC
Greetings, when implementing the Android Performance Tuner (1.5.2) for our Unity 2022.3.5f1 project, we noticed we were getting the following Errors in Android Logcat:

**App Startup**
![image](https://github.com/android/tuningfork/assets/24323750/53d05593-0dfc-4e37-b5f1-bdf3d23e6878)

With each Upload Request
![image](https://github.com/android/tuningfork/assets/24323750/c8b545cc-c289-4769-a84d-bf195547585b)

I noticed in a [closed issue](https://github.com/android/tuningfork/issues/16) that it was mentioned a fix for the first two (and possibly the third if related) was in progress, is this still the case?  We are just a bit concerned about adding unknown errors to our project while attempting to resolve existing stability issues.

**Comment by labalov** [comment] 2023-08-24 16:49
Thanks for the issue. We've identified the root cause for these errors and we should have them resolved by the next update to our unity plugin. 

Also I'd like to point out that this issue should not disrupt the flow of the library as it only fails to obtain a portion of the memory telemetry that's being collected on the device.

**Comment by Ditronian** [comment] 2023-08-24 17:10
> Thanks for the issue. We've identified the root cause for these errors and we should have them resolved by the next update to our unity plugin.
> 
> Also I'd like to point out that this issue should not disrupt the flow of the library as it only fails to obtain a portion of the memory telemetry that's being collected on the device.

Thanks, we appreciate it and will keep an eye out for it!

**Comment by labalov** [comment] 2023-11-09 13:32
The newest alpha release should fix this issue.

**Closed by labalov** 2023-11-09 13:32 UTC
