### ISSUE TITLE
Settings not updating across computers (sourcetree/git)

### ISSUE THREAD

**Issue by abittman** [android/tuningfork#11] opened 2021-08-17 23:39 UTC
We've noticed a bug with the Android Performance Tuner's settings not being saved correctly, or not being loaded correctly when added to git (sourcetree).

On my computer, when I go to the settings for this project, I observe the following annotation parameter settings in the window:
![image](https://user-images.githubusercontent.com/10857352/129813329-9d857179-bd2f-4ef1-9581-f922c7908dde.png)

However, when the changed settings files are pushed through sourcetree and loaded on my colleague's computer, he sees the following:
![image](https://user-images.githubusercontent.com/10857352/129813269-42f57ca5-6970-405f-896c-864f52eb2c11.png)

Additionally, if he changes from "Use default parameters" to "Use custom parameters", the newest field I added to test this is also missing:
![image](https://user-images.githubusercontent.com/10857352/129813309-4115ef4b-0af2-444d-8425-ffaf175bdd3b.png)

Further additionally, if I swap to a branch that doesn't have the performance tuner, and then swap back, it says I have unsaved changes and expects me to use default parameters? As follows:
![image](https://user-images.githubusercontent.com/10857352/129814100-0d37afbc-0a28-4a9d-a04a-cf7448fc6908.png)

I assume the settings here are either not being saved or loaded correctly when tested across computers using a repository. 

Let me know if I can provide any more details on the matter.

**Comment by hdtx** [comment] 2021-08-24 18:40
Hi @abittman, thanks for the report. Could you please list the following for your (and your colleague's) machine:
- OS version
- Plugin version
- Unity version

**Comment by abittman** [comment] 2021-08-24 22:50
Hey @hdtx,

My machine is running:
* Windows 10 (v10.0.19043)
* Android Performance Tuner v1.1.2
* Unity 2019.4.17f1

My colleague is running:
* macOS Big Sur (Version 11.5.2)
* Android Performance Tuner v1.1.2
* Unity 2019.4.17f1

**Comment by bilck** [comment] 2021-10-01 14:39
We notice a very similar problem related to this post and [this one](https://github.com/android/tuningfork/issues/8).

**Comment by jfouk** [comment] 2021-12-09 23:35
I'm running into the same problem, I edit on a Windows PC, and build my projects in a gitlab runner. The resulting build is set to default annotation, even though on my PC it is set to custom. This is the log I get from the build:

`[17:24:43][Warning]Android Performance Tuner: Don't set annotation when default annotation enabled`

I do also get this error, which might be caused by Unity picking up my custom annotation setup, since I added a new field, but default still being set?

>[17:23:28][Error]SetCurrentAnnotation({ "scene": "SCENE_ASSETS_SCENES_LOADINGSCENE" }) result is InvalidAnnotation
Google.Android.PerformanceTuner.AndroidPerformanceTuner`2:OnSceneChanged(Scene, Scene)
Google.Android.PerformanceTuner.AndroidPerformanceTuner`2:EnableDefaultAnnotationsMode()
Google.Android.PerformanceTuner.AndroidPerformanceTuner`2:StartInternal()
Assets.Scripts.Utilities.<Start>d__3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by eristella** [comment] 2022-02-11 12:55
Hello, this issue has been fixed in the latest release.
Could you please upgrade to the latest version?

Thanks!

**Closed by eristella** 2022-02-11 12:55 UTC
