### ISSUE TITLE
Problems making the upload request - Error 35 when sending UPLOAD request - "Android Performance Tuner Unity v1.5.0 (2022-02-10)

### ISSUE THREAD

**Issue by josemgmz** [android/tuningfork#15] opened 2022-02-11 09:46 UTC
Hello,

I am trying to integrate Android Performace Tuner into my game using unity 3d engine.

I have followed all the steps of the codelab, but I cannot send the reports.

I have make sure before:
- Use a version higher than unity 2019.3.14.
- Use a higher version .NET version 4.X.
- Enable frame pacing.
- Use the most recent version of Android Performance Tuner specifically: "Android Performance Tuner Unity v1.5.0 (2022-02-10)".
- Internet Access Requires.
- I have created an API KEY in our Cloud Google project for this service and i have done it as commented in the guides.

Errors: 

2022-02-11 10:26:25.954 16358-16451/? I/TuningFork: Got settings from tuningfork/tuningfork_settings.bin
2022-02-11 10:26:25.954 16358-16451/? I/TuningFork: Using local file cache at /data/user/0/MyAppPackageName/cache/tuningfork
2022-02-11 10:26:25.956 16358-16451/? I/TuningForkUtils: OpenGL version 3.2 
2022-02-11 10:26:25.962 16358-16451/? I/TuningFork: TuningFork.GoogleEndpoint: OK
2022-02-11 10:26:25.962 16358-16451/? E/TuningFork: Could not open /proc/0/status
2022-02-11 10:26:25.962 16358-16451/? I/TuningFork: TuningFork Settings:
      method: 1
      interval: 30000
      n_ikeys: 4
      n_annotations: 1
      n_histograms: 4
      base_uri: https://performanceparameters.googleapis.com/v1/
      api_key: hide
      fp filename: dev_tuningfork_fidelityparams_1.bin
      itimeout: 1000
      utimeout: 100000
2022-02-11 10:26:25.962 16358-16451/? I/TuningFork: Settings::Histograms
2022-02-11 10:26:25.962 16358-16451/? I/TuningFork: ikey: 64000 min: 6.540000 max: 60.000000 nbkts: 200
2022-02-11 10:26:25.962 16358-16451/? I/TuningFork: ikey: 64001 min: 10.000000 max: 40.000000 nbkts: 30
2022-02-11 10:26:25.962 16358-16451/? I/TuningFork: ikey: 64003 min: 0.000000 max: 20.000000 nbkts: 30
2022-02-11 10:26:25.962 16358-16451/? I/TuningFork: ikey: 64002 min: 0.000000 max: 20.000000 nbkts: 30
2022-02-11 10:26:25.962 16358-16451/? I/TuningFork: Got PAUSED histograms: {"name": "applications/MyAppPackageName/apks/20300", "session_context": {"device": {"brand": "OPPO", "build_version": "30", "cpu_core_freqs_hz": [2000000000, 2000000000, 2000000000, 2000000000, 2000000000, 2000000000, 2200000000, 2200000000], "device": "OP4B65L1", "fingerprint": "OPPO/CPH1951EEA/OP4B65L1:11/RP1A.200720.011/1638281965681:user/release-keys", "gles_version": {"major": 3, "minor": 2}, "model": "CPH1951", "product": "CPH1951EEA", "soc_manufacturer": "", "soc_model": "", "swap_total_bytes": 4294963200, "total_memory_bytes": 7978815488}, "game_sdk_info": {"session_id": "b1b659f2-517f-4164-8fe4-eca87d8ad506", "swappy_version": "1.3.0", "version": "1.5.0"}, "time_period": {"end_time": "2022-02-11T09:23:28.034969Z", "start_time": "2022-02-11T09:20:28.043513Z"}}, "telemetry": [{"context": {"annotations": "CAM=", "duration": "179.991456318s", "tuning_parameters": {"experiment_id": "", "serialized_fidelity_parameters": ""}}, "report": {"battery": {"battery_event": [{"app_on_foreg
2022-02-11 10:26:25.963 16358-16451/? I/TuningFork: Deserializing saved session
2022-02-11 10:26:25.963 16358-16451/? I/TuningFork: TuningFork initialized
2022-02-11 10:26:25.976 16358-16648/? E/TuningFork: Could not open /proc/0/oom_score
2022-02-11 10:26:55.980 16358-16647/? W/TuningFork.GE: Error 35 when sending UPLOAD request
    {"name": "applications/MyAppPackageName/apks/20300", "session_context": {"crash_reports": [{"crash_reason": 0, "session_id": "b1b659f2-517f-4164-8fe4-eca87d8ad506"}], "device": {"brand": "OPPO", "build_version": "30", "cpu_core_freqs_hz": [2000000000, 2000000000, 2000000000, 2000000000, 2000000000, 2000000000, 2200000000, 2200000000], "device": "OP4B65L1", "fingerprint": "OPPO/CPH1951EEA/OP4B65L1:11/RP1A.200720.011/1638281965681:user/release-keys", "gles_version": {"major": 3, "minor": 2}, "model": "CPH1951", "product": "CPH1951EEA", "soc_manufacturer": "", "soc_model": "", "swap_total_bytes": 4294963200, "total_memory_bytes": 7978815488}, "game_sdk_info": {"session_id": "8472e944-ff9d-467f-a091-0786d57df4a5", "swappy_version": "1.3.0", "version": "1.5.0"}, "time_period": {"end_time": "2022-02-11T09:26:55.953760Z", "start_time": "2022-02-11T09:26:26.339386Z"}}, "telemetry": [{"context": {"annotations": "", "duration": "5.875865847s", "tuning_parameters": {"experiment_id

The errors i mainly see are:

2022-02-11 10:26:25.962 16358-16451/? E/TuningFork: Could not open /proc/0/status
2022-02-11 10:26:25.976 16358-16648/? E/TuningFork: Could not open /proc/0/oom_score
2022-02-11 10:26:55.980 16358-16647/? W/TuningFork.GE: Error 35 when sending UPLOAD request

What could be wrong?

Regards

**Comment by eristella** [comment] 2022-02-11 12:52
Hi @josemgmz, is your connection metered?
If you're on a Windows machine, you can check whether the connection is metered by right-clicking on the network in the Wi-fi panel > Settings > Metered connection.
If that's the case, could you try disabling the metered connection and trying again?

Let me know if that works :)

**Comment by josemgmz** [comment] 2022-02-11 15:28
Hi @eristella thank you for you reply.

In my case, i'm wired, although i see that i also have the metered connection option, this on my computer is disabled by default.

**Comment by eristella** [comment] 2022-02-11 17:42
Could you look for a "internet reachability" line in the log and paste it here? 

Thanks!

**Comment by josemgmz** [comment] 2022-02-14 15:32
Hi, After re-compiling a version i now get the error code had change to 15, the error:


2022-02-14 16:23:09.830 30875-31372/MyAppPackageName I/TuningFork:Web: Connecting to: https://performanceparameters.googleapis.com/v1/applications/MyAppPackageName/apks/20205:uploadTelemetry
2022-02-14 16:23:10.092 30875-31372/MyAppPackageName I/TuningFork:Web: Response code: 403
2022-02-14 16:23:10.092 30875-31372/MyAppPackageName I/TuningFork:Web: Response message: Forbidden
2022-02-14 16:23:10.093 30875-31372/MyAppPackageName W/TuningFork:Web: java.io.FileNotFoundException: https://performanceparameters.googleapis.com/v1/applications/MyAppPackageName/apks/20205:uploadTelemetry
2022-02-14 16:23:10.093 30875-31372/MyAppPackageName W/TuningFork.GE: Error 15 when sending UPLOAD request
{"name": "applications/MyAppPackageName/apks/20205", "session_context": {"device": {"brand": "OPPO", "build_version": "30", "cpu_core_freqs_hz": [2000000000, 2000000000, 2000000000, 2000000000, 2000000000, 2000000000, 2200000000, 2200000000], "device": "OP4B65L1", "fingerprint": "OPPO/CPH1951EEA/OP4B65L1:11/RP1A.200720.011/1638281965681:user/release-keys", "gles_version": {"major": 3, "minor": 2}, "model": "CPH1951", "product": "CPH1951EEA", "soc_manufacturer": "", "soc_model": "", "swap_total_bytes": 4294963200, "total_memory_bytes": 7978815488}, "game_sdk_info": {"session_id": "fe7c2dcf-f4db-41e6-9a4a-f631c7867b8e", "swappy_version": "1.3.0", "version": "1.5.0"}, "time_period": {"end_time": "2022-02-14T15:23:09.805504Z", "start_time": "2022-02-14T15:22:40.181142Z"}}, "telemetry": [{"context": {"annotations": "", "duration": "6.153275769s", "tuning_parameters": {"experiment_id": "", "serialized_fidelity_parameters": ""}}, "report": {"battery": {"battery_event": [{"app_

i cannot find "internet reachability" line in the log displayed in android studio.

Something quite strange that I have noticed is that from Unity the panel looks like this, no matter how many times i restart unity.

![imagen](https://user-images.githubusercontent.com/23422849/153893795-06bd8369-2ccd-44d0-9d57-3109a5d8c908.png)

**Comment by eristella** [comment] 2022-02-14 16:36
Does your Android Manifest include the ACCESS_NETWORK_STATE permission?

**Comment by josemgmz** [comment] 2022-02-15 09:20
It's a bit weird though, the option in unity Internet Access is require, the android manifest doesn't include it.

![imagen](https://user-images.githubusercontent.com/23422849/154027996-d6bbf528-578e-4582-a1c0-6e8e89d825e7.png)

This is my manifest:
![imagen](https://user-images.githubusercontent.com/23422849/154030473-427c9a2b-ef90-4741-ab3d-4db75550d23f.png)

<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

I have added in the manifest these two lines, and the error code 15 is gone, but again I have the error code 35

![imagen](https://user-images.githubusercontent.com/23422849/154031398-58abcf37-3306-4f4f-88df-e47ac6a3746d.png)


2022-02-15 10:18:16.145 21948-22630/MyAppPackageName W/TuningFork.GE: Error 35 when sending UPLOAD request
    {"name": "applications/MyAppPackageName/apks/20300", "session_context": {"crash_reports": [{"crash_reason": 0, "session_id": "be709660-63f5-42c8-8844-60462d3a359c"}], "device": {"brand": "OPPO", "build_version": "30", "cpu_core_freqs_hz": [2000000000, 2000000000, 2000000000, 2000000000, 2000000000, 2000000000, 2200000000, 2200000000], "device": "OP4B65L1", "fingerprint": "OPPO/CPH1951EEA/OP4B65L1:11/RP1A.200720.011/1638281965681:user/release-keys", "gles_version": {"major": 3, "minor": 2}, "model": "CPH1951", "product": "CPH1951EEA", "soc_manufacturer": "", "soc_model": "", "swap_total_bytes": 4294963200, "total_memory_bytes": 7978815488}, "game_sdk_info": {"session_id": "306c2618-a0c9-44cc-9863-3d428d4d2a38", "swappy_version": "1.3.0", "version": "1.5.0"}, "time_period": {"end_time": "2022-02-15T09:18:16.123039Z", "start_time": "2022-02-15T09:17:46.546261Z"}}, "telemetry": [{"context": {"annotations": "", "duration": "5.127528846s", "tuning_parameters": {"experiment_id


Regards

**Comment by eristella** [comment] 2022-02-15 17:04
Is the APT Window still empty? There might have been problems when importing the package if the Window is not showing correctly. Could you try removing the plugin and reimporting it?
Also, how are you starting APT? [This line ](https://github.com/android/tuningfork/blob/master/Runtime/Scripts/AndroidPerformanceTunerInternal.cs#:~:text=Debug.LogFormat(%22internet%20reachability%20is%20%7B0%7D%22%2C%20internetReachability)%3B) should be appearing in the logs when you call the Start() function on your APTuner.

**Comment by josemgmz** [comment] 2022-02-15 20:24
After restarting Unity few times i got the APT window working.

![imagen](https://user-images.githubusercontent.com/23422849/154143202-661c6015-a372-4276-8968-5db0daf672f3.png)

I found that log:

2022-02-15 21:20:06.865 10734-10795/MyAppPackageName I/Unity: internet reachability is ReachableViaCarrierDataNetwork

And on the debug log the errorCode returned after calling the Start()

Android Performance Tuner started with code: Ok

**Comment by eristella** [comment] 2022-02-21 11:05
Hello, I checked internally and not allowing updates via metered connections is the intended behaviour. Your data is cached and is later uploaded when a non-metered connection is found. Could you try connecting your phone to a wifi and see whether it still has the same issue?

**Comment by nathan-mag** [comment] 2022-03-09 15:10
Hi @eristella - I have a similar issue to the original poster of this issue. I have tried all the solutions you suggested but I still get the same error (this is from my Android logcat). 

<img width="1281" alt="Screenshot 2022-03-09 at 15 03 06" src="https://user-images.githubusercontent.com/71647590/157469538-15a4f23b-999b-40af-a54b-d76660abee28.png">

When I import the package to Unity, I get a security alert about the "protoc" executable - I did the usual Mac steps of allowing this exe to run on my machine, but I still get this error every time I try to run it on device. 

Please can you help me understand what may be causing the APT to still not work?

**Comment by ata-matthewm** [comment] 2022-04-14 21:28
I'm also seeing the same Error 15 under the same circumstances, on the same version of the library (1.5.0)

- Unity 2019.4.35f1
- Using .NET 4.X
- Frame pacing + vsync enabled as per the guide
- ACCESS_NETWORK_STATE and INTERNET permissions are in the manifest.
- Internet reachability is ReachableViaLocalAreaNetwork
- API key was added and correctly displays in TuningFork Settings via logcat

Happy to provide more information it would help get this solved.

**Closed** 2023-07-18 13:39 UTC

**Comment by purnapatadia** [comment] 2023-08-10 05:33
Facing the same error logs. 
Any help would be appreciated.
